import type { Metadata } from "next";
import "./globals.css";
import localFont from "next/font/local";


const redHatText = localFont({
  src: [
    { path: "./fonts/static/RedHatText-Regular.ttf", weight: "400", style: "normal" },
    { path: "./fonts/static/RedHatText-SemiBold.ttf", weight: "600", style: "normal"},
    { path: "./fonts/static/RedHatText-Bold.ttf", weight: "700", style: "normal" },
  ],
  variable: "--font-red-hat-text",
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${redHatText.variable} antialiased text-base`}
      >
        {children}
      </body>
    </html>
  );
}
